# Generated by Django 5.2.6 on 2025-09-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('helper', 'Helper')], default='staff', max_length=20),
        ),
    ]
